# Dataset
csv_filepath: interview_data.csv
train_test_pct: 0.8
train_val_pct: 0.8

# Hyperparameters
batch_size: 64 # how many independent sequences will we process in parallel?
# block_size: 256 # what is the maximum context length for predictions?
block_size: 32 # what is the maximum context length for predictions?
max_iters: 5000
eval_interval: 500
learning_rate: 3e-4
eval_iters: 200
n_embd: 384
n_head: 6
n_layer: 6
dropout: 0.2